<?php

/**
 * Precificação
 * Essa API auxiliará na formação de preços dos mais variados produtos. Com cálculos de custo, de preço de venda e de margem de lucro.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fernando.junior@thorgus.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class LucroApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation lucroGet
     *
     * Calcule a Margem de Lucro aplicada sobre o Custo Total Unitário..
     *
     *
     * @return Http response
     */
    public function lucroGet()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['venda'])) {
            throw new \InvalidArgumentException('Missing the required parameter $venda when calling lucroGet');
        }
        $venda = $input['venda'];

        if (!isset($input['custo'])) {
            throw new \InvalidArgumentException('Missing the required parameter $custo when calling lucroGet');
        }
        $custo = $input['custo'];

        if (!isset($input['encargos'])) {
            throw new \InvalidArgumentException('Missing the required parameter $encargos when calling lucroGet');
        }
        $encargos = $input['encargos'];

        $valor = round(abs(
          $venda*(1-$encargos)-$custo
        ),2);

        $porcentagem = round(abs(
          $valor * 100 / $custo
        ),2);

        return response()->json(['valor' => $valor, 'porcentagem' => $porcentagem]);
    }
}
